### ISSUE TITLE
module seems not work for java files

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/environments#1]
after I load module, such as GATK or picard, i can't use the command directly like
```
java -jar picard.jar
```
or
```
java -jar GenomeAnalysisTK.jar
```
Do these command work differently? or do they just not work with modules?

**Comment by cdeboever3** [comment]
Looks like a permissions issue. Try giving execute permissions. Compare to blat below.

    [/software]fl-hn1 $ ls -lh blat.linux.x86_64.v287/
    -rwxr-xr-x 1 cdeboever users 1.8M Aug  6  2013 blat
    [/software]fl-hn1 $ ls -lh GenomeAnalysisTK-3.4-46/
    -rw-r--r-- 1 hel070 users  13M Jul  9 14:41 GenomeAnalysisTK.jar

**Comment by hurleyLi** [comment]
It still give me this err:
```
Error: Unable to access jarful GenomeAnalysisTK.jar
```

**Comment by hurleyLi** [comment]
It's funny, when you do
```
which GenomeAnalysisTK.jar
/frazer01/software/GenomeAnalysisTK-3.4-46/GenomeAnalysisTK.jar
```
it gives you the right path...

**Comment by cdeboever3** [comment]
It seems that jar files cannot be added to the path ([see here](http://gatkforums.broadinstitute.org/discussion/2899/howto-install-all-software-packages-required-to-follow-the-gatk-best-practices)). I've changed the module file. Try loading GATK and using as follows:

    [~]fl-hn1 $ module load GATK
    [~]fl-hn1 $ java -jar $GATK

**Comment by hurleyLi** [comment]
It works! It looks like picard need to be set up in the same way...

**Comment by cdeboever3** [comment]
Yep, I changed it as well. Try java -jar $picard. If that works, we can
close this. I'm going to add a note to the wiki about jar files.

**Comment by hurleyLi** [comment]
It works well! Thanks man!
